config/routes.rb
Goalsetter::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :destroy, :index]
  resource :session, only: [:new, :create, :destroy]

  resources :goals, except: :show do
    member do
      post 'complete', to: 'goals#complete'
    end
  end

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  user_id    :integer          not null
#  private    :boolean          not null
#  completed  :boolean          not null
#  created_at :datetime
#  updated_at :datetime
#

class Goal < ActiveRecord::Base
  validates :name, :user, :presence => true
  validates :private, :completed, inclusion: { in: [true, false] }

  belongs_to :user
  before_validation :public_by_default, :incomplete_by_default

  private

    def public_by_default
      self.private ||= false
      true
    end

    def incomplete_by_default
      self.completed ||= false
      true
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  password_digest :string(255)
#  token           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  admin           :boolean
#

class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :password_digest, :token, :presence => true
  validates :password, :length => { minimum: 6, allow_nil: true }
  validates :username, :token, :uniqueness => true

  has_many :goals, :inverse_of => :user
  before_validation :set_token, :admin_default

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_token!
    self.token = User.generate_token
    self.save!
    self.token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  private

    def set_token
      self.token ||= User.generate_token
    end

    def admin_default
      self.admin ||= false
      true
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  def login!(user)
    session[:token] = user.reset_token!
  end

  def logout!
    current_user.reset_token!
    session[:token] = nil
  end

  def check_logged_in
    redirect_to new_session_url unless logged_in?
  end




end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :check_logged_in

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes(goal_params)
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    user = goal.user
    goal.destroy!
    redirect_to user_url(user)
  end

  def index
    if logged_in?
      @goals = Goal.where("user_id = ? OR private = ?", current_user.id, false)
    else
      @goals = Goal.where("private = ?", false)
    end
    render :index
  end

  def complete
    @goal = Goal.find(params[:id])
    @goal.completed = !@goal.completed
    @goal.save

    redirect_to :back
  end

  private

    def goal_params
      params.require(:goal).permit(:name, :private, :completed)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
        params[:user][:password])

    if !!@user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "Username or password is invalid"
      @user = User.new(username: params[:user][:username])
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_logged_in, only: [:show, :index]

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end


  def show
    @user = User.find(params[:id])
    render :show
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    return nil if session[:token].nil?
    @current_user ||= User.find_by(token: session[:token])
  end

  def logged_in?
    !!current_user
  end

  def admin?
    current_user.admin
  end

  def privileged?(user)
    admin? || current_user.id == user.id
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
Edit Goal

<form action="<%= goal_url(@goal) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>What is your goal?
    <input type="text" name="goal[name]" value="<%= @goal.name %>">
  </label>

  <label>
    <input
      type="checkbox"
      name="goal[private]"
      value="true"
      <%= 'checked' if @goal.private %>>
    Private
  </label>

  <label>
    <input
      type="checkbox"
      name="goal[completed]"
      value="true"
      <%= 'checked' if @goal.completed %>>
    Completed
  </label>


  <p><input type="submit" value="Update Goal"></p>
</form>

app/views/goals/index.html.erb
All Goals

<ul>
  <% @goals.each do |goal| %>
  <li>
    <%= goal.name %>
    <% if goal.user_id == current_user.id %>
      <%= link_to "Edit", edit_goal_url(goal) %>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/goals/new.html.erb
New Goal

<form action="<%= goals_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>What is your goal?
    <input type="text" name="goal[name]" value="<%= @goal.name %>">
  </label>

  <label>
    <input type="checkbox" name="goal[private]" value="<%= true %>">
    Private
  </label>

  <label>
    <input type="checkbox" name="goal[completed]" value="<%= true %>">
    Completed
  </label>


  <p><input type="submit" value="Add Goal"></p>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goalsetter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if logged_in? %>
    <%= current_user.username %>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>

  <%= flash[:errors] %>

  <%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
  <li><%= link_to user.username, user_url(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

  <button>Sign Up</button>
</form>

app/views/users/show.html.erb
<h1>Goals for <%= @user.username %></h1>

<ul>
  <% @user.goals.each do |goal| %>
  <% next if goal.private && !privileged?(@user) %>

  <li>
    <div class="goal-item">
      <% disabled = !privileged?(@user) %>
      <% btn_class = goal.completed ? "btn-complete" : "btn-incomplete" %>

      <%= button_to "&#10003;".html_safe, complete_goal_url(goal),
        class: btn_class, disabled: disabled %>

      <%= goal.name %>

      <% if privileged?(@user) %>
        <%= link_to "Edit", edit_goal_url(goal) %>
        <%= button_to "Remove Goal", goal_url(goal), method: :delete %>
      <% end %>
    </div>
  </li>
  <% end %>
</ul>

<% if privileged?(@user) %>
  <%= button_to 'Remove Account', user_url(@user), method: :delete %>
<% end  %>

<% if current_user.id == @user.id %>
  <%= link_to 'Add New Goal', new_goal_url %>
<% end %>